jazzy \
  --clean \
  --author "Paweł Madej" \
  --author_url https://pawelmadej.com \
  --github_url https://github.com/nysander/twitter-text \
  --github-file-prefix https://github.com/nysander/twitter-text/tree/0.0.1 \
  --root-url https://nysander.github.io/twitter-text/ \
  --module-version 0.0.1 \
  --module TwitterText \
  --output docs \
  --swift-build-tool spm \
